### ISSUE TITLE
FaceTecModule   Is null for IOS

### ISSUE THREAD

**Issue by Edgarb-Claims-Conf** [GoodDollar/ReactNativeFaceTec#9] opened 2021-06-13 11:18 UTC
### Description
FaceTecModule.js file
_import { NativeModules } from 'react-native'
const { FaceTecModule } = NativeModules
export default FaceTecModule_

 **FaceTecModule** -  can't extract object from Native Modules, null for IOS. But android side getting object

 Gets Abort Trap 6 Error as well (screenshot attached)

### Steps to reproduce
1. Created new project
2.  npm install @gooddollar/react-native-facetec --save, cd ios && pod install
3. running the App

![Abort Trap 6 error](https://user-images.githubusercontent.com/83900665/121804923-81618000-cc51-11eb-98be-9b35d57a5835.jpeg)
![Error](https://user-images.githubusercontent.com/83900665/121804931-8d4d4200-cc51-11eb-91ea-7851b569cec7.jpeg)

 Getting Error,  'null is not an object' (evaluating '_FaceTecModule.default.getConstants')

**Comment by mdcuk34** [comment] 2021-06-30 13:22
Hey @Edgarb-Claims-Conf, we had the same problem while integrating this into our app. I believe the problem is due to the latest version of Swift and Xcode 12. However you can resolve this for now by adding the following to your `Podfile`:
```
  add_flipper_pods!('Flipper' => '0.78.0')
  post_install do |installer|
    flipper_post_install(installer)
    # react-native-facetec requires wholemodule compilation to be
    # enabled for both debug and release for the build to work.
    # Related to Swift versions and Xcode version 12.
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-facetec'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        end
      end
    end
  end
```

**Comment by johnsmith-gooddollar** [comment] 2022-01-10 10:36
"Abort Trap" issue was fixed in this one and next two commits: https://github.com/GoodDollar/ReactNativeFaceTec/commit/0855a17c77f75f17f8c301644922acc4529e0c76

**Closed by johnsmith-gooddollar** 2022-01-10 10:36 UTC
